### ISSUE TITLE
Participant profile update is not working

### ISSUE THREAD

**Issue by mayanksh99** [dsckiet/website-backend-v2#42]
- Type:  error

- Module: Participant

- Description: The participant update route is giving status 200 but the profile is not updated after the request is made.

- To reproduce: Made a request to update a participant profile

Screenshot/gif

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44022198/87203531-70f9a480-c320-11ea-929c-e912ced45d7e.gif)

**Comment by ritiksr25** [comment]
resolved: data format received from frontend changed

**Comment by rhnmht30** [comment]
> resolved: data format received from frontend changed

Was this resolved in a specific PR?
Can you link it here?

**Comment by ritiksr25** [comment]
> > resolved: data format received from frontend changed
> 
> Was this resolved in a specific PR?
> Can you link it here?

it was frontend issue, they changed the request data format
